"""Extracts ONLY the significant-variant columns (from the list produced by
step1) out of the large genetic file (cfg.raw_file), without loading the
entire matrix (millions of columns) into memory. Writes a small file (id +
N significant variants), generation-agnostic just like cfg.raw_file (the
generation is applied later, when merging with the environment -- same
scheme as vcf_pipeline/build_dataset.py).

NOTE ON COLUMN READING: pyarrow selects columns by NAME from the parquet
schema. build_dataset.py currently reads the whole file and then recovers
the sample id from the DataFrame's INDEX (not from an explicit "id" column
in the schema) -- for a selective read we need to know the name of that
column/index in the file's physical schema, which varies depending on how
it was written (a named index vs "__index_level_0__" auto-generated by
pandas for unnamed indices). Use `--inspect-schema` BEFORE running the
actual extraction, on a file you trust, to verify the heuristic below
finds the right column -- if it doesn't, it fails with an explicit error
instead of silently producing a file with no id.
"""
from __future__ import annotations

import argparse
import os

import pandas as pd
import pyarrow.parquet as pq

from gene_environment.config import get_config
from gene_environment.logging_utils import configure_logging, get_logger
from gene_environment.utils.id_utils import clean_sample_id
from gene_environment.vcf_pipeline.build_dataset import NON_GEN_COLS

log = get_logger(__name__)

# Typical names pandas/pyarrow use to materialize the index as a physical
# column in the parquet file when the index has no explicit name.
_INDEX_LIKE_PREFIXES = ("__index_level_",)


def _detect_id_columns(schema_names: list[str]) -> list[str]:
    candidates = [c for c in schema_names if c in NON_GEN_COLS]
    candidates += [c for c in schema_names if c.startswith(_INDEX_LIKE_PREFIXES)]
    return candidates


def inspect_schema(raw_file: str) -> None:
    pf = pq.ParquetFile(raw_file, thrift_string_size_limit=2_000_000_000, thrift_container_size_limit=2_000_000_000)
    names = pf.schema.names
    id_cols = _detect_id_columns(names)
    print(f"Total columns in schema: {len(names)}")
    print(f"First 10 columns: {names[:10]}")
    print(f"Heuristically detected id/index columns: {id_cols}")
    if not id_cols:
        print("WARNING: no id/index column recognized -> extraction would fail. "
              "Look at 'First 10 columns' above and manually figure out which one holds the sample id.")


def load_significant_labels(path: str) -> list[str]:
    with open(path) as f:
        return [line.strip() for line in f if line.strip()]


def run(labels_path: str, out_path: str, raw_file: str | None = None) -> str:
    cfg = get_config()
    configure_logging(cfg.log_dir)
    raw_file = raw_file or cfg.raw_file

    labels = load_significant_labels(labels_path)
    if not labels:
        log.warning("No variants in list %s. Exiting.", labels_path)
        return ""
    log.info("%d variants to extract from %s", len(labels), raw_file)

    pf = pq.ParquetFile(raw_file, thrift_string_size_limit=2_000_000_000, thrift_container_size_limit=2_000_000_000)
    schema_names = set(pf.schema.names)
    id_cols = _detect_id_columns(pf.schema.names)
    if not id_cols:
        raise RuntimeError(
            f"Cannot find the id/index column in the schema of {raw_file}. "
            f"Rerun with --inspect-schema to see the column names and, if needed, "
            f"adjust _detect_id_columns()."
        )

    present = [v for v in labels if v in schema_names]
    missing = [v for v in labels if v not in schema_names]
    if missing:
        log.warning("%d/%d significant variants NOT present in %s (filtered upstream by MAF/LD-prune?): %s",
                    len(missing), len(labels), raw_file, missing[:20] if len(missing) > 20 else missing)
    if not present:
        log.warning("No significant variants present in raw_file. Exiting.")
        return ""

    columns_to_read = id_cols + present
    log.info("Reading %d columns (of which %d id/index) from %s", len(columns_to_read), len(id_cols), raw_file)
    table = pf.read(columns=columns_to_read, use_pandas_metadata=True)
    df = table.to_pandas()

    # normalize the id like build_dataset.py does, whatever the physical
    # name of the found id column is
    id_col = next((c for c in id_cols if c in df.columns), None)
    if id_col is None and df.index.name in id_cols:
        df = df.reset_index()
        id_col = df.columns[0]
    if id_col is None:
        raise RuntimeError(
            f"The detected id columns ({id_cols}) ended up neither among the columns nor in the "
            f"index of the resulting DataFrame -- manual check needed."
        )
    df = df.rename(columns={id_col: "id"})
    df["id"] = df["id"].astype(str).map(clean_sample_id)

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    df.to_parquet(out_path, engine="pyarrow", index=False)
    log.info("Extraction complete: %d samples x %d variants -> %s", df.shape[0], len(present), out_path)
    return out_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--labels", type=str, default="./output/significant_variants.txt")
    parser.add_argument("--out", type=str, default="./output/significant_genetic_matrix.parquet")
    parser.add_argument("--raw-file", type=str, default=None, help="Default: config.raw_file")
    parser.add_argument("--inspect-schema", action="store_true", help="Only inspect the schema and exit, without extracting anything")
    args = parser.parse_args()

    if args.inspect_schema:
        cfg = get_config()
        inspect_schema(args.raw_file or cfg.raw_file)
    else:
        run(args.labels, args.out, args.raw_file)