#!/usr/bin/env python3
"""
interpret_plink_output.py
==========================

Takes the STANDARD plink2 outputs (generated by 00_run_plink_qc.sh) and
answers 3 operational questions:
  1) Is an LMM needed for relatedness?
  2) Do the PCs belong in the main model, or is sensitivity enough?
  3) Is there genomic inflation in your scan (if you provide p-values)?

Unlike qc_report.py, here kinship and PCA have already been computed by
plink2 (a standard, validated tool) -- this script only does the
statistical interpretation relative to your exposure variable.

INPUT
-----
--kin0        king.kin0 file produced by: plink2 --make-king-table
--eigenvec    pca.eigenvec file produced by: plink2 --pca 10
--metadata    csv/parquet with columns: id, <exposure-col>
              (id must match plink2's IID column)
--exposure-col name of the exposure column in the metadata
--pvalues     optional: csv/parquet with a p-value column from your scan
--pvalue-col  p-value column name (default: p)
--pi-hat-threshold  PI_HAT threshold (default 0.125); note: plink2's
              KINSHIP is already KING-robust's phi, so PI_HAT = 2 * KINSHIP
--strip-doubled-id  if the IID is in 'NAME_NAME' form (both halves
              identical -- typical when FamilyID=IndividualID in the
              source VCF), reduce it to 'NAME' before merging with
              --metadata. Off by default: only turn this on if you know
              your IID convention doubles the name, and check the
              "IDs left unchanged" count this prints -- see
              plink_io.strip_doubled_ids(). Use the SAME setting here as
              you use for extract_pca_covariates.py, since both scripts
              need to agree on what an IID looks like for the same cohort.

USAGE
-----
python interpret_plink_output.py \
    --kin0 qc_output/king.kin0 \
    --eigenvec qc_output/pca.eigenvec \
    --metadata sample_metadata.csv \
    --exposure-col exposure_agri_score \
    --pvalues gwas_results.csv --pvalue-col p \
    --strip-doubled-id \
    --out-dir diagnostics_output
"""

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:
    plt = None

from plink_io import load_eigenvec, load_kinship, strip_doubled_ids


def summarize_relatedness(kin_df, pi_hat_threshold):
    kin_df = kin_df.copy()
    kin_df["PI_HAT"] = 2 * kin_df["KINSHIP"]
    n_pairs = len(kin_df)
    flagged = kin_df[kin_df["PI_HAT"] > pi_hat_threshold].sort_values("PI_HAT", ascending=False)
    n_above = len(flagged)
    pct_above = 100 * n_above / n_pairs if n_pairs > 0 else np.nan

    # Flag "near-identical" pairs (PI_HAT > 0.9) separately: likely a
    # technical duplicate across batches, not real biological relatedness.
    likely_duplicates = kin_df[kin_df["PI_HAT"] > 0.9]

    return kin_df, flagged, n_pairs, n_above, pct_above, likely_duplicates


def correlate_pcs_with_exposure(eigenvec_df, metadata_df, exposure_col, n_pcs, strip_doubled_id):
    from scipy.stats import pearsonr

    eigenvec_df = eigenvec_df.copy()
    if strip_doubled_id:
        eigenvec_df["IID_clean"] = strip_doubled_ids(eigenvec_df["IID"], label="eigenvec IID")
    else:
        eigenvec_df["IID_clean"] = eigenvec_df["IID"]

    merged = eigenvec_df.merge(metadata_df, left_on="IID_clean", right_on="id", how="inner")

    n_matched = len(merged)
    n_meta = len(metadata_df)
    n_eig = len(eigenvec_df)

    pc_cols = [c for c in merged.columns if c.startswith("PC")][:n_pcs]
    print("NA PCs:", merged[pc_cols].isna().sum().sum())
    exposure = merged[exposure_col].astype(float).values

    valid = ~np.isnan(exposure)
    exposure_v = exposure[valid]
    pcs_v = merged.loc[valid, pc_cols].values

    corr_per_pc = []
    for i, col in enumerate(pc_cols):
        r, p_val = pearsonr(pcs_v[:, i], exposure_v)
        corr_per_pc.append({"PC": col, "pearson_r": round(float(r), 4), "p_value": float(p_val)})

    from numpy.linalg import lstsq
    X = np.column_stack([pcs_v, np.ones(pcs_v.shape[0])])
    beta, _, _, _ = lstsq(X, exposure_v, rcond=None)
    pred = X @ beta
    ss_res = np.sum((exposure_v - pred) ** 2)
    ss_tot = np.sum((exposure_v - exposure_v.mean()) ** 2)
    r_squared = 1 - ss_res / ss_tot if ss_tot > 0 else np.nan

    return corr_per_pc, r_squared, n_matched, n_meta, n_eig, merged, pc_cols


def genomic_inflation_factor(pvalues):
    from scipy.stats import chi2
    p = np.asarray(pvalues, dtype=float)
    p = p[~np.isnan(p)]
    p = np.clip(p, 1e-300, 1)
    chi2_obs = chi2.isf(p, df=1)
    return float(np.median(chi2_obs) / 0.4549364)


def qq_plot(pvalues, out_path):
    """
    QQ-plot of observed vs. expected -log10(p) under H0 (uniform). Visual
    complement to lambda GC: a single number can hide inflation
    concentrated in the tail (a few strongly deviating variants) that the
    QQ-plot makes visible at a glance, as typically requested in a paper.
    """
    if plt is None:
        return None
    p = np.asarray(pvalues, dtype=float)
    p = p[~np.isnan(p)]
    p = np.clip(p, 1e-300, 1)
    p_sorted = np.sort(p)
    n = len(p_sorted)
    if n == 0:
        return None
    expected = -np.log10(np.arange(1, n + 1) / (n + 1))
    observed = -np.log10(p_sorted)

    fig, ax = plt.subplots(figsize=(5.5, 5.5))
    ax.scatter(expected, observed, s=6, alpha=0.5, color="steelblue")
    max_val = max(expected.max(), observed.max())
    ax.plot([0, max_val], [0, max_val], color="red", linestyle="--", linewidth=1, label="expected (H0)")
    ax.set_xlabel("expected -log10(p)")
    ax.set_ylabel("observed -log10(p)")
    ax.set_title("QQ-plot")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--kin0", required=True)
    parser.add_argument("--eigenvec", required=True)
    parser.add_argument("--metadata", required=True)
    parser.add_argument("--exposure-col", default="exposure")
    parser.add_argument("--pvalues", default=None)
    parser.add_argument("--pvalue-col", default="p")
    parser.add_argument("--pi-hat-threshold", type=float, default=0.125)
    parser.add_argument("--n-pcs", type=int, default=10)
    parser.add_argument(
        "--strip-doubled-id", action="store_true",
        help="reduce 'NAME_NAME' IIDs to 'NAME' before merging with --metadata (off by default; see module docstring)",
    )
    parser.add_argument("--out-dir", default="diagnostics_output")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = []
    summary = {}

    def log(msg):
        print(msg)
        lines.append(msg)

    log("=" * 70)
    log("PLINK2 OUTPUT INTERPRETATION - pre-analysis screening for G x E")
    log("=" * 70)

    # ---------------- metadata ----------------
    if args.metadata.endswith(".csv"):
        metadata_df = pd.read_csv(args.metadata)
    else:
        metadata_df = pd.read_parquet(args.metadata)
    if "id" not in metadata_df.columns:
        log(f"ERROR: column 'id' not found in {args.metadata}. "
            f"Columns found: {list(metadata_df.columns)}")
        return

    # ---------------- 1. relatedness ----------------
    log("\n" + "-" * 70)
    log("1) RELATEDNESS (from king.kin0, computed by plink2)")
    log("-" * 70)

    kin_raw = load_kinship(args.kin0)
    kin_df, flagged, n_pairs, n_above, pct_above, likely_dup = summarize_relatedness(
        kin_raw, args.pi_hat_threshold
    )

    log(f"Total pairs reported by plink2: {n_pairs}")
    log(f"PI_HAT threshold: {args.pi_hat_threshold}")
    log(f"Pairs above threshold: {n_above} ({pct_above:.4f}% of total)")
    summary["n_pairs_total"] = int(n_pairs)
    summary["pi_hat_threshold"] = float(args.pi_hat_threshold)
    summary["n_pairs_above_threshold"] = int(n_above)
    summary["pct_pairs_above_threshold"] = float(pct_above)
    summary["n_likely_duplicates"] = int(len(likely_dup))

    if len(likely_dup) > 0:
        log(f"\n>>> WARNING: {len(likely_dup)} pairs have PI_HAT > 0.9 "
            "(near-identical). Likely a TECHNICAL DUPLICATE across "
            "batches, not real biological relatedness. Check these IDs "
            "before proceeding:")
        for _, row in likely_dup.head(20).iterrows():
            log(f"    {row['IID1']} - {row['IID2']}: PI_HAT={row['PI_HAT']:.4f}")

    real_relatedness = flagged[flagged["PI_HAT"] <= 0.9]
    if len(real_relatedness) > 0:
        log(f"\nPairs with plausible relatedness (0.125 < PI_HAT <= 0.9): {len(real_relatedness)}")
        for _, row in real_relatedness.head(20).iterrows():
            log(f"    {row['IID1']} - {row['IID2']}: PI_HAT={row['PI_HAT']:.4f}")

    if pct_above < 1.0:
        log("\n>>> VERDICT: <1% of pairs above threshold. An LMM is probably "
            "not needed in the main analysis (after removing any technical "
            "duplicates across batches).")
        summary["lmm_verdict"] = "not needed"
    else:
        log("\n>>> VERDICT: >=1% of pairs above threshold. Seriously consider "
            "an LMM, or at minimum exclude one member of each flagged pair "
            "from the main analysis.")
        summary["lmm_verdict"] = "consider LMM / exclude one member per flagged pair"

    if plt is not None and n_pairs > 0:
        plt.figure(figsize=(6, 4))
        plt.hist(kin_df["PI_HAT"], bins=80)
        plt.axvline(args.pi_hat_threshold, color="red", linestyle="--", label="threshold")
        plt.xlabel("PI_HAT (2 x plink2 KINSHIP)")
        plt.ylabel("N pairs")
        plt.title("PI_HAT distribution")
        plt.legend()
        plt.tight_layout()
        plt.savefig(out_dir / "pi_hat_distribution.png", dpi=150)
        plt.close()
        log(f"[chart: {out_dir / 'pi_hat_distribution.png'}]")

    # ---------------- 2. PCs vs exposure ----------------
    log("\n" + "-" * 70)
    log("2) PCs vs EXPOSURE")
    log("-" * 70)

    eigenvec_df = load_eigenvec(args.eigenvec)
    corr_per_pc, r_squared, n_matched, n_meta, n_eig, merged, pc_cols = correlate_pcs_with_exposure(
        eigenvec_df, metadata_df, args.exposure_col, args.n_pcs, args.strip_doubled_id
    )

    log(f"Samples in eigenvec: {n_eig} | in metadata: {n_meta} | matched: {n_matched}")
    summary["n_eigenvec"] = int(n_eig)
    summary["n_metadata"] = int(n_meta)
    summary["n_matched"] = int(n_matched)
    if n_matched < min(n_eig, n_meta) * 0.9:
        log("  WARNING: low match rate between metadata id and plink2 IID. "
            "Check the naming convention (e.g. FID_IID vs plain IID) -- "
            "if IIDs look like 'NAME_NAME', try --strip-doubled-id.")

    log("\nCorrelation (Pearson) PCs vs exposure:")
    for row in corr_per_pc:
        flag = "  <-- notable" if abs(row["pearson_r"]) > 0.2 and row["p_value"] < 0.05 else ""
        log(f"    {row['PC']}: r={row['pearson_r']:.4f}, p={row['p_value']:.2e}{flag}")

    # Supplementary table for the paper (not just log text): one row per
    # PC with r, p-value and a notability flag, ready to include as a
    # supplementary table.
    corr_table = pd.DataFrame(corr_per_pc)
    corr_table["notable"] = (corr_table["pearson_r"].abs() > 0.2) & (corr_table["p_value"] < 0.05)
    corr_csv_path = out_dir / "pc_exposure_correlation.csv"
    corr_table.to_csv(corr_csv_path, index=False)
    log(f"[table: {corr_csv_path}]")

    log(f"\nR^2 (exposure ~ {' + '.join(pc_cols)}): {r_squared:.4f} "
        f"({r_squared:.1%} of exposure variance explained by ancestry)")
    summary["pc_exposure_r2"] = float(r_squared)
    summary["pc_exposure_r2_pct"] = float(100 * r_squared)

    if r_squared > 0.10:
        log("\n>>> VERDICT: R^2 > 10%. Concrete ancestry-exposure confounding. "
            "PCs belong in the MAIN MODEL, not just as a sensitivity check.")
        summary["pc_verdict"] = "include in main model"
    elif r_squared > 0.03:
        log("\n>>> VERDICT: moderate confounding (3-10%). Recommended to include "
            "them in the base model; keep them in sensitivity analyses too.")
        summary["pc_verdict"] = "recommended in base model"
    else:
        log("\n>>> VERDICT: R^2 < 3%. Negligible confounding. PCs as a "
            "sensitivity check only is a defensible choice.")
        summary["pc_verdict"] = "sensitivity check is sufficient"

    if plt is not None:
        plt.figure(figsize=(6, 5))
        sc = plt.scatter(merged[pc_cols[0]], merged[pc_cols[1]],
                          c=merged[args.exposure_col], cmap="viridis", s=25)
        plt.colorbar(sc, label=args.exposure_col)
        plt.xlabel(pc_cols[0])
        plt.ylabel(pc_cols[1])
        plt.title("PC1 vs PC2 colored by exposure")
        plt.tight_layout()
        plt.savefig(out_dir / "pca_vs_exposure.png", dpi=150)
        plt.close()
        log(f"[chart: {out_dir / 'pca_vs_exposure.png'}]")

    # ---------------- 3. lambda GC ----------------
    log("\n" + "-" * 70)
    log("3) LAMBDA GC")
    log("-" * 70)
    if args.pvalues:
        if args.pvalues.endswith(".csv"):
            pval_df = pd.read_csv(args.pvalues)
        else:
            pval_df = pd.read_parquet(args.pvalues)
        pvals = pval_df[args.pvalue_col].values
        lam = genomic_inflation_factor(pvals)
        n_tests = int((~np.isnan(pvals)).sum())
        log(f"N tests: {n_tests} | Lambda GC = {lam:.4f}")
        summary["lambda_gc_n_tests"] = n_tests
        summary["lambda_gc"] = float(lam)
        if lam > 1.05:
            log(">>> VERDICT: lambda > 1.05, possible residual stratification.")
            summary["lambda_gc_verdict"] = "possible residual stratification"
        else:
            log(">>> VERDICT: lambda within an acceptable range.")
            summary["lambda_gc_verdict"] = "acceptable"

        qq_path = out_dir / "qq_plot.png"
        saved = qq_plot(pvals, qq_path)
        if saved:
            log(f"[chart: {qq_path}]")
        elif plt is None:
            log("  (matplotlib not available, QQ-plot skipped)")
    else:
        log("No --pvalues provided, skipping this check.")

    log("\n" + "=" * 70)
    log("SUMMARY")
    log("=" * 70)
    log(f"- LMM: {summary.get('lmm_verdict', 'n/a')}")
    log(f"- PCs in base model: {summary.get('pc_verdict', 'n/a')}")

    (out_dir / "diagnostics_report.txt").write_text("\n".join(lines), encoding="utf-8")
    log(f"\nReport saved to: {out_dir / 'diagnostics_report.txt'}")

    # Structured summary for build_supplementary_report.py: this is what
    # that script reads (rather than regex-scraping the .txt above), so a
    # future wording change to the log lines above can't silently break
    # the Word report.
    (out_dir / "diagnostics_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    log(f"Structured summary saved to: {out_dir / 'diagnostics_summary.json'}")


if __name__ == "__main__":
    main()
